[build]
  command = "npm run build"
  publish = ".next"
  base = "/"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/team/*"
  to = "/team/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/platform/*"
  to = "/platform/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextServer"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Content-Security-Policy = "default-src 'self' *.bolt.new; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; connect-src 'self' wss: https:;"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[functions]
  directory = "netlify/functions"
  included_files = ["dist/**"]
  node_bundler = "esbuild"

[dev]
  framework = "next"
  targetPort = 3000

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://api.production.example.com"
  NEXT_PUBLIC_CDN_URL = "https://cdn.production.example.com"
  NEXT_PUBLIC_BASE_PATH = "/fitness"

[context.staging.environment]
  NEXT_PUBLIC_API_URL = "https://api.staging.example.com"
  NEXT_PUBLIC_CDN_URL = "https://cdn.staging.example.com"
  NEXT_PUBLIC_BASE_PATH = "/fitness"

[context.development.environment]
  NEXT_PUBLIC_API_URL = "http://localhost:3000"
  NEXT_PUBLIC_CDN_URL = ""
  NEXT_PUBLIC_BASE_PATH = ""

[[plugins]]
  package = "@netlify/plugin-gatsby-cache"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "https://api.staging.example.com"
  NEXT_PUBLIC_CDN_URL = "https://cdn.staging.example.com"
  NEXT_PUBLIC_BASE_PATH = "/fitness"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://api.staging.example.com"
  NEXT_PUBLIC_CDN_URL = "https://cdn.staging.example.com"
  NEXT_PUBLIC_BASE_PATH = "/fitness" 