apiVersion: v1
kind: Secret
metadata:
  name: transcription-secrets
type: Opaque
data:
  openai-api-key: "${OPENAI_API_KEY_BASE64}"
  service-api-key: "${SERVICE_API_KEY_BASE64}"

---
apiVersion: v1
kind: Secret
metadata:
  name: transcription-db-credentials
type: Opaque
data:
  username: "${POSTGRES_USER_BASE64}"
  password: "${POSTGRES_PASSWORD_BASE64}"

---
apiVersion: v1
kind: Secret
metadata:
  name: transcription-rabbitmq-credentials
type: Opaque
data:
  username: "${RABBITMQ_USER_BASE64}"
  password: "${RABBITMQ_PASSWORD_BASE64}"

---
apiVersion: v1
kind: Secret
metadata:
  name: transcription-s3-credentials
type: Opaque
data:
  access-key: "${S3_ACCESS_KEY_BASE64}"
  secret-key: "${S3_SECRET_KEY_BASE64}" 