apiVersion: v1
kind: PersistentVolume
metadata:
  name: clip-data-pv
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: high-performance-ssd
  csi:
    driver: csi.storage.k8s.io
    volumeAttributes:
      type: ssd
      performance: high
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clip-data-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: high-performance-ssd
---
apiVersion: v1
kind: StorageClass
metadata:
  name: high-performance-ssd
provisioner: csi.storage.k8s.io
parameters:
  type: ssd
  performance: high
  redundancy: 3
  encryption: "true"
  backup: "true"
  tier: hot 